
<!DOCTYPE html>
<html lang="en">
<head>
<base href="<?= BASE_URL ?>">
<link rel="stylesheet" href="css/style.css">
<nav >
  <div >
    <a href="home">PELISPASS</a>
    <div >
      <ul>
        <li>
          <a href="categorias">Categorias</a>
        </li>
        <li>
          <a href="login">Log in</a>
        </li>
        <li>
          <a href="logout">Log Out</a>
        </li>
        <li>
          <a href="editar">Editar Catalogo</a>
        </li>

      </ul>
    </div>
  </div>
</nav>
</head>

</html>