
<!DOCTYPE html>
<html lang="en">
<head>
<base href="<?= BASE_URL ?>">
<title>Pelispass</title>
<link rel="stylesheet" href="css/style.css">
<nav class = "navbar">
  <div class = "navbar__container">
    <a href="home" class = "navbar__logo">PELISPASS</a>
      <ul class="navbar__menu">
        <li><a href="categorias">Categorias</a></li>
        <li><a href="login">Log in</a></li>
        <li><a href="logout">Log Out</a></li>
        <li><a href="editar">Editar Catalogo</a></li>
      </ul>
  </div>
</nav>
</head>

</html>