<?php require_once 'layouts/header.phtml' ?>
<div class="catalog">
  <h1 class = "catalog__title">Editar Películas</h1>
  
  <a class ="addmovie__link" href="agregar"><h4>Agregar pelicula</h4></a>

  <div class="card_container">
    <?php foreach ($movies as $movie): ?>
        <div class="card">
          <img class="card__image" src="<?= $movie->img ?>" alt="Portada de <?= $movie->title ?>">
          <h5 class="card__title"><?= $movie->title ?></h5>
          <p class="card__text"><strong>Director:</strong> <?= $movie->director ?></p>
          <p class="card__text"><strong>Género:</strong> <?= $movie->genre ?></p>
          <a class="card__link" href="pelicula/<?= $movie->id ?>" >Leer mas</a>
          <a class="card__link" href="editar/<?= $movie->id ?>" >Editar</a>
          <a class="card__link" href="eliminar/<?= $movie->id ?>" >Eliminar</a>
        </div>
    <?php endforeach; ?>
  </div>
</div>

<?php require_once 'layouts/footer.phtml' ?>