<?php require_once 'layouts/header.phtml' ?>
<div>
  <h1>Editar Películas</h1>
  
  <div>
  <a href="agregar"><h4>Agregar pelicula</h4></a>
    <?php foreach ($movies as $movie): ?>
      <div>
        <div>
          <img src="<?= $movie->img ?>" alt="Portada de <?= $movie->title ?>">
          <div>
            <h5><?= $movie->title ?></h5>
            <p ><strong>Director:</strong> <?= $movie->director ?></p>
            <p ><strong>Género:</strong> <?= $movie->genre ?></p>
            <a href="pelicula/<?= $movie->id ?>" >Leer mas</a>
            <a href="editar/<?= $movie->id ?>" >Editar</a>
            <a href="eliminar/<?= $movie->id ?>" >Eliminar</a>
          </div>
        </div>
      </div>
    <?php endforeach; ?>
  </div>
</div>

<?php require_once 'layouts/footer.phtml' ?>