<?php require 'templates/layouts/header.phtml' ?>

<form class="login__form" method='post' action='login'>
    <div class="login__label">
        <label for='username'>Nombre de Usuario</label>
        <input type='text' id='username' name='username' required>
    </div>
    <div>
        <label class="login__label" for='password'>Password</label>
        <input type='password' id='password' name='password' required>
    </div>
    <button class="login__button" type='submit'>Login</button>
</form>

<?php require 'templates/layouts/footer.phtml' ?>