
<?php require_once 'layouts/header.phtml' ?>

<div>
<form action="update/<?= $movie->id ?>" method="POST">
    <div>
        <div>
            <div>
                <label>Título</label>
                <input required name="title" type="text"value="<?= $movie->title ?>">
            </div>
        </div>
        <div>
            <div>
                <label>Director</label>
                <input required name="director" type="text" value="<?= $movie->director ?>">
            </div>
        </div>

        <div>
            <div>
                <label>Genero</label>
                <select required name="genre">
                    <?php foreach ($genres as $genre) : ?>
                        <option value="<?= $genre->id ?>"> <?= $genre->genre ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
        <div>
            <div>
                <label>Portada</label>
                <input required name="img" type="text" value="<?= $movie->img ?>"> 
            </div>
        </div>
    </div>

    <div>
        <label>Descripcion</label>
        <textarea name="descrip" rows="3" value="<?= $movie->descrip ?>"></textarea>
    </div>

    <button type="submit">Guardar</button>
</form>
</div>

<?php require_once 'layouts/footer.phtml' ?>