<?php require_once 'layouts/header.phtml' ?>

<h1 class="genre__title">Categorias</h1>

<div class="genre__container">
    <?php foreach ($genres as $genre): ?>
        <a class= "genre__link" href="categoria/<?= $genre->id ?>"><?= $genre->genre ?></a>
    <?php endforeach ?>
    <a class ="edit__link"href="editar/categoria">Editar Categorias</a>
</div>


<?php require_once 'layouts/footer.phtml' ?>

