<?php require_once 'layouts/header.phtml'; ?>

<div>
    <div>
        <div>
            <div>
                <img src="<?= $movie->img ?>" alt="Portada de <?= $movie->title ?>">
                <div>
                    <h5 ><?= $movie->title ?></h5>
                    <p><strong>Director:</strong> <?= $movie->director ?></p>
                    <p> <strong>Género:</strong> <?= $movie->genre ?></p>
                    <p> <strong>Descripción:</strong> <?= $movie->descrip ?></p>
                    <a href="home">Volver al catalogo</a>
                </div>
            </div>
        </div>
    </div>
</div>

<?php require_once 'layouts/footer.phtml'; ?>